### ISSUE TITLE
JNIC Compatible

### ISSUE THREAD

**Issue by Soukazes** [nuym/Jnic#1]
Hello,

Thanks for creating this program.

And is it possible to make it compatible with Minecraft? please because when i use it on a mod and run my game i crash: 

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: dev/jnic/ew0liX/Loader 
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 32767

I tested on several different mods and still the same crash !

Thank you for your response and have a good day.

**Comment by nuym** [comment]
You are the first user, so I am very happy, I would like to ask you need the English version?

**Comment by Soukazes** [comment]
Thank you for your reply, yes here are 1 mod and yes i would like an English version if possible. (the mod is in 1.7.10 forge) 

https://www.mediafire.com/file/t4vxpz0pax80nab/TestMod-1.0.jar/file

**Comment by nuym** [comment]
After my day of fixing and testing, I finally learned that it was Minecraft Mod had a Deobfuscator method that caused the loading to fail because JNICLoader.class used crash obfuscation to make it impossible to determine that, this problem only occurs on mods, for other java programs like client, spigot, etc. This problem only occurs on mod, for client, spigot and other java programs are compatible, I am now fixing the file jnic.bin, please wait patiently for a day, thank you for your support :D

Translated with www.DeepL.com/Translator (free version)

**Comment by Soukazes** [comment]
All right, thank you in advance

**Comment by Soukazes** [comment]
Just a question, How can I use vmprotect on it?

**Comment by nuym** [comment]
I apologize for replying so late because the problem is with jnic.bin_dump.zip which is the original file of a JnicLoader who is obfuscated with a crasher, I was not involved in the development of this JnicLoader so I don't have the source code and I asked someone else about it but he expressed his apologies because their team split up, the repository was deleted cleanly, can not find the source code, but for other Java programs, it is applicable.

Translated with www.DeepL.com/Translator (free version)

**Comment by nuym** [comment]
For VMP, you need to download it at the bottom of the README, it's a cracked software, it's a Chinese download link, you may download it slowly, when VMP appears in the CMD, you just need to open the TestMod folder in the java -jar JNIC.jar TestMod.jar TestMod, there's a dll or so with a suffix of file, drag it to VMP and add protection, I'm not sure if there is an English version of VMP because it's cracked, you can find how to use VMP on the internet, thanks for your support of my project.

Translated with www.DeepL.com/Translator (free version)

**Comment by Soukazes** [comment]
Hello, so thank you for your reply and infact it's good I managed to make it compatible with Minecraft mods ! I edited the code of the NativeObfuscator class so that it doesn't change the signatures.

Well, have a good day.

**Comment by nuym** [comment]
> Hello, so thank you for your reply and infact it's good I managed to make it compatible with Minecraft mods ! I edited the code of the NativeObfuscator class so that it doesn't change the signatures.
> 
> 
> 
> Well, have a good day.

cool,Could you please pull the request?

**Comment by Soukazes** [comment]
uh withdraw the request that is to say?

**Comment by nuym** [comment]
>  pull the request that is to say?

yup,i mean i want to know that how to fix it. sorry,my spoken english is bad

**Comment by Soukazes** [comment]
You just have to remove the changeSignature function which is in the NativeObfuscator class
