### ISSUE TITLE
未混淆的加载程序

### ISSUE THREAD

**Issue by micartey** [nuym/Jnic#3]
是否可以添加未混淆的加载程序？我从另一个问题中得知你没有来源。也许下面的项目会对你有所帮助，基本上是一样的。加载程序以二进制形式包含在此处。也许它背后的代码没有被混淆

https://github.com/MyJ2c/Open-MyJ2c/tree/main

(Google Translate)

**Comment by nuym** [comment]
我已了解那个项目，那个项目具有处理时间慢和无法运行等问题，而且我也认识那个作者，我询问他了，他说他们的组织由于利益分配不均，遭到删库，所以丢失了Loader的源码，我现在再尽力还原它，但是我能确保里面没有后门，你仅仅只需要加密data.dat就可以。也许未来的某一天他们找到了源码或者混淆被处理了，我现在就在处理混淆，感谢你对项目的支持。

I already know about that project, that project has problems with slow processing time and not working, and I also know the author, I asked him about it and he said that their organization lost the Loader source code due to the deletion of libraries due to unequal distribution of benefits, I'm trying my best to restore it now but I can make sure that there is no backdoor in it, you just need to encrypt the data.dat only. Maybe sometime in the future they find the source code or the obfuscation is dealt with, I'm dealing with the obfuscation right now, thanks for your support of the project.

Translated with www.DeepL.com/Translator (free version)

**Comment by nuym** [comment]
那个 myj2c.bin文件一样具有混淆和加密。
That myj2c.bin file is just as obfuscated and encrypted.

**Comment by nuym** [comment]
I will add English version when i deobf loader

**Comment by nuym** [comment]
Hi here is loader,but it has a lot of problem,it's not recognized by my JNIC, I think it's a problem with the anonymous inner class,maybe you can try to fix it :(
https://github.com/nuym/JNICLoader
